### ISSUE TITLE
Feature Request – Config-less operation

### ISSUE THREAD

**Issue by Succubyss** [FloGa/upnp-daemon#2]
I'm using this to dynamically open ports for torrenting with aria2 and it's working very well. However, having to generate a CSV file makes my script less elegant than I would like.

I'd like if there was a way to get the options to upnp-daemon entirely through the command line, even if it's just piping a newline-separated CSV string in through stdin, or even passing a JSON-equivalent to a parameter.

Another option would be a parameter corresponding to each column, though it'd have to either be limited to one address per execution, or there would have to be a separator as well as making sure each corresponding parameter has the same amount of separators.

**Comment by FloGa** [comment]
Hi! Thank you for using my little program and giving feedback!

> I'd like if there was a way to get the options to upnp-daemon entirely through the command line, even if it's just piping a newline-separated CSV string in through stdin, or even passing a JSON-equivalent to a parameter.

I really like this idea! I'll start with accepting a full CSV file on stdin, this should be doable pretty fast. JSON is also something I wanted to try, maybe it's time now to tackle this, too.

> Another option would be a parameter corresponding to each column

This is not something I think would scale nicely ... As you said yourself, there need to be additional checks to make sure you give the same amount of elements for each parameter. I could imagine this makes it hard to actually use the CLI properly.

Let's go with the stdin approach for now. I'll keep you updated here!

**Comment by FloGa** [comment]
The current develop branch supports reading a CSV file from stdin. Are you able to test this and see if it fits your needs? (See https://github.com/FloGa/upnp-daemon/blob/c6e803aae23ed336da52bc0b75972149205bfa2b/README.md#reading-from-standard-input for example usage.)

**Comment by FloGa** [comment]
I also implemented JSON as a config file format, given either as a real file or via stdin. (See https://github.com/FloGa/upnp-daemon/blob/0c9b7dc742ec13d2c84d2879d071683e84c26b17/README.md#json for example usage.)

**Comment by FloGa** [comment]
[Release 0.4.0](https://github.com/FloGa/upnp-daemon/releases/tag/0.4.0) includes the noted changes.

I'm closing this issue for now. If you still have problems, don't hesitate to re-open this or open a new issue!
