### ISSUE TITLE
Replacing get_if_addrs-sys with local-ip-address

### ISSUE THREAD

**Issue by Succubyss** [FloGa/upnp-daemon#3]
`README.md` states that if an IP address isn't listed in a column that it will check each gateway until one reports success.

On Windows, you can end up with a whole lot of different network interfaces added through things like WSL, Bluestacks, Hyper-V, VPNs, and so on.

It might be better to use the `local-ip-address` crate instead, which is compatible with _"Linux, Windows, and macOS (and other BSD-based systems)"_, according to its documentation.

https://crates.io/crates/local-ip-address
https://github.com/EstebanBorai/local-ip-address

**Comment by FloGa** [comment]
Hi again!

The point here is, if you don't give an IP address, then how should the program know on what interface it should send the UPnP request? Say you have two legit network interfaces, wlan and eth. Actually, even Hyper-V and VPNs and so on can be included here, for a program that uses these interfaces it just doesn't matter what "type" of network interface it is, they just see a bunch of IP addresses. On which one should we send the request? eth? wlan? vpn? Even using the `local-ip-address` crate, we could never be sure we get the correct address that you intended to use.

By providing the "use the first interface that gives a positive response" approach, I help people in "simple" scenarios, where there actually is only one network interface that responds successfully.

In your case, how about I support giving the IP address in CIDR notation? This way, if your desired network's DHCP gives you an address between 192.168.178.1 and 192.168.178.254, you could give the IP address as `192.168.178.0/24` and I only send the request via the interface that matches this CIDR range. Is this something that would fit your use case?

**Comment by FloGa** [comment]
The current development branch supports IP addresses in CIDR notation. See https://github.com/FloGa/upnp-daemon/blob/1f1c2d5a723bda6a54c17465fd757c06b52d5704/README.md#fields.

If nothing comes up in the next days, I'll create a new release.

**Comment by FloGa** [comment]
[Release 0.4.0](https://github.com/FloGa/upnp-daemon/releases/tag/0.4.0) includes the noted changes.

I'm closing this issue for now. If you still have problems, don't hesitate to re-open this or open a new issue!
